server:
   port: 8081

  #our department service should connect to our service registry of:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Department

    username: postgres
    password: Password

  jpa:
    hibernate:
      ddl-auto: create-drop

  zipkin:
    base-url: http://127.0.0.1:9411/






