server:
  port: 8082

  #our employee service should connect to our service registry of:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee

    username: postgres
    password: Password

  jpa:
    hibernate:
      ddl-auto: create-drop

  zipkin:
    base-url: http://127.0.0.1:9411/


management:
  tracing:
    sampling:
      probability: 1.0

  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      employeeService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      employeeService:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      employeeService:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s